feat: add blink.cmp hlgroups
rebelot/kanagawa.nvim pull request #263
Opened 2024-11-22 10:21 UTC by jonsch318

Nothing should really change, since blink already reads most of these from pmenu per default. However explicitly defining this is better in my opinion. I orientated myself on the existing Cmp groups.

2024-12-25 19:45 UTC, aliaksandr-trush commented on lua/kanagawa/highlights/plugins.lua
> +        BlinkCmpItemKindText = { fg = theme.ui.fg },
Should it be just BlinkCmpKind<kind> as it described in https://github.com/Saghen/blink.cmp/blob/main/docs/configuration/appearance.md ?

2025-01-01 12:25 UTC, WieeRd requested changes

2025-01-01 12:25 UTC, WieeRd commented on lua/kanagawa/highlights/plugins.lua
Most of the blink menu highlights are meant to be consistent with `Pmenu*` groups.
So `{ link = "Pmenu*" }` or `theme.ui.pmenu.*` should be preferred if possible.
The end result is the same regardless of using links or directly accessing the palette.
But if the user (me, for example :P) happens to be customizing the theme through `.setup()`,
using links will properly propagate the changes to `Pmenu*` to plugin highlights.

2025-01-01 12:25 UTC, WieeRd commented on lua/kanagawa/highlights/plugins.lua
Just realized you mostly copied the `nvim-cmp` groups from below.
I think the same changes should be applied to cmp groups as well.
Guess I'll write a PR^2 to your PR, to avoid duplicate PRs on this main repo.

2025-01-01 12:51 UTC, WieeRd commented on lua/kanagawa/highlights/plugins.lua
> +        BlinkCmpLabelDeprecated = { fg = theme.syn.comment, strikethrough = true },
Never mind this, just realized that using `NonText` for deprecated items makes it practically invisible on the default pmenu bg. I wasn't aware of this because I was using darker pmenu bg. But my point about the ghost text still stands.

2025-01-01 13:30 UTC, WieeRd commented on lua/kanagawa/highlights/plugins.lua
> +        BlinkCmpItemKindCopilot = { link = "String" },
Have you not tested your PR at all?
`blink.cmp` uses `BlinkCmpKind*`, not `BlinkCmpItemKind*`.
I was so confused what was going on with item highlights not applying...

2025-01-01 13:32 UTC, WieeRd commented on lua/kanagawa/highlights/plugins.lua
> +        BlinkCmpItemKindCopilot = { link = "String" },
Fixed in https://github.com/jonsch318/forked-kanagawa.nvim/pull/1

2025-01-01 13:33 UTC, WieeRd commented on lua/kanagawa/highlights/plugins.lua
> +        BlinkCmpItemKindText = { fg = theme.ui.fg },
Addressed in my PR^2 https://github.com/jonsch318/forked-kanagawa.nvim/pull/1.

2025-01-03 15:04 UTC, WieeRd commented
- #271

2025-01-03 20:33 UTC, closed without merging